[workspace]
resolver = "2"

members = [
    "main",
    "common",
    "day_one",
    "day_two",
    "day_three",
    "day_four",
    "day_five",
    "day_six",
    "day_seven",
    "day_eight",
]

[workspace.dependencies]
indoc = "2"
lazy_static = "1.4.0"
regex = "1.10.2"