name: Release run

on:
  workflow_run:
    workflows: ["Build and test"]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Initialize Energy Estimation
      uses: green-coding-berlin/eco-ci-energy-estimation@v2
      with:
        task: start-measurement
      continue-on-error: true
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout Measurement
      uses: green-coding-berlin/eco-ci-energy-estimation@v2
      with:
        task: get-measurement
        label: 'Checkout'
      continue-on-error: true
    - name: Build Release
      run: cargo build --verbose --release
    - name: Build Measurement
      uses: green-coding-berlin/eco-ci-energy-estimation@v2
      with:
        task: get-measurement
        label: 'Build Release'
      continue-on-error: true
    - name: Run all days
      run: cargo run --release
    - name: Release run measurement
      uses: green-coding-berlin/eco-ci-energy-estimation@v2
      with:
        task: get-measurement
        label: 'Release run'
      continue-on-error: true
    - name: Show Energy Results
      uses: green-coding-berlin/eco-ci-energy-estimation@v2
      with:
        task: display-results
      continue-on-error: true
